apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: main
          image: redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.01"
              memory: "10Mi"
            requests:
              cpu: "0.01"
              memory: "10Mi"
      restartPolicy: Always

