apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: fluent
  labels:
    app: fluent-bit
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-fat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      name: fluent-bit
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: main
          image: fluent/fluent-bit:2.0.11
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.01"
              memory: "10Mi"
            requests:
              cpu: "0.01"
              memory: "10Mi"
      restartPolicy: Always
